#pragma once


#if !defined(HYPODERMIC_OVERRIDE_CONSTRUCTOR_ARGUMENT_COUNT)
# define HYPODERMIC_CONSTRUCTOR_ARGUMENT_COUNT 20
#else
# define HYPODERMIC_CONSTRUCTOR_ARGUMENT_COUNT HYPODERMIC_OVERRIDE_CONSTRUCTOR_ARGUMENT_COUNT
#endif